import "server-only";

import type { Organization } from "@/domain/schemas/organization";
import { parseOrganization } from "@/domain/schemas/organization";
import { DEMO_DOMAIN_TENANT_ID } from "@/domain/demo-constants";
import {
  DATASET_DECLARATION,
  FINANCIAL_INSTITUTIONS_ADAPTER_VERSION,
  FINANCIAL_INSTITUTIONS_VERTICAL_ID,
  type FinancialInstitutionPayload,
} from "@/verticals/financial-institutions/schema";

const CREATED = "2026-01-15T12:00:00.000Z";
const UPDATED = "2026-03-01T15:30:00.000Z";

type Seed = {
  n: number;
  displayName: string;
  legalName?: string;
  organizationType: "synthetic_bank" | "synthetic_credit_union";
  regionCode: FinancialInstitutionPayload["operatingRegions"][number];
  localityLabel: string;
  tags: string[];
  payload: Omit<FinancialInstitutionPayload, "schemaVersion" | "syntheticDeclaration">;
};

/**
 * Exactly 24 deterministic fictional financial institutions.
 * Names are unmistakably synthetic and must not resemble real institutions.
 */
const SEEDS: readonly Seed[] = [
  {
    n: 1,
    displayName: "Northbridge Example Credit Union",
    legalName: "Northbridge Example Credit Union Cooperative",
    organizationType: "synthetic_credit_union",
    regionCode: "REGION_NORTH_DEMO",
    localityLabel: "Illustrative Northeast",
    tags: ["demo-complete", "credit-union"],
    payload: {
      institutionKind: "synthetic_credit_union",
      serviceAreaType: "single_region",
      operatingRegions: ["REGION_NORTH_DEMO"],
      balanceSheetScaleBand: "band_m",
      ownershipModel: "synthetic_cooperative",
      digitalServiceMaturity: "established",
      lendingBreadth: "moderate",
      operatingComplexityBand: "moderate",
      publicChangeSignals: [
        {
          label: "Synthetic charter update notice",
          reference: "synthetic://financial-institutions/org_syn_fi_001/change/charter",
          observedAt: "2026-02-10T10:00:00.000Z",
        },
      ],
      regulatoryDataAvailability: "abundant_synthetic",
    },
  },
  {
    n: 2,
    displayName: "Cedar Hollow Sample Bank",
    organizationType: "synthetic_bank",
    regionCode: "REGION_MID_DEMO",
    localityLabel: "Illustrative Midwest",
    tags: ["demo-partial", "bank"],
    payload: {
      institutionKind: "synthetic_bank",
      serviceAreaType: "multi_region",
      operatingRegions: ["REGION_MID_DEMO", "REGION_NORTH_DEMO"],
      balanceSheetScaleBand: "band_l",
      ownershipModel: "synthetic_stock",
      digitalServiceMaturity: "developing",
      lendingBreadth: "broad",
      operatingComplexityBand: "high",
      publicChangeSignals: [],
      regulatoryDataAvailability: "moderate_synthetic",
    },
  },
  {
    n: 3,
    displayName: "Harborline Demo Institution",
    organizationType: "synthetic_bank",
    regionCode: "REGION_WEST_DEMO",
    localityLabel: "Illustrative West",
    tags: ["demo-stale", "bank"],
    payload: {
      institutionKind: "synthetic_bank",
      serviceAreaType: "single_region",
      operatingRegions: ["REGION_WEST_DEMO"],
      balanceSheetScaleBand: "band_s",
      ownershipModel: "synthetic_mutual",
      digitalServiceMaturity: "emerging",
      lendingBreadth: "narrow",
      operatingComplexityBand: "low",
      publicChangeSignals: [
        {
          label: "Synthetic branch footprint note",
          reference: "synthetic://financial-institutions/org_syn_fi_003/change/footprint",
          observedAt: "2024-06-01T08:00:00.000Z",
        },
      ],
      regulatoryDataAvailability: "sparse_synthetic",
    },
  },
  {
    n: 4,
    displayName: "Lumenridge Synthetic Credit Union",
    organizationType: "synthetic_credit_union",
    regionCode: "REGION_SOUTH_DEMO",
    localityLabel: "Illustrative South",
    tags: ["demo-restricted", "credit-union"],
    payload: {
      institutionKind: "synthetic_credit_union",
      serviceAreaType: "single_region",
      operatingRegions: ["REGION_SOUTH_DEMO"],
      balanceSheetScaleBand: "band_m",
      ownershipModel: "synthetic_cooperative",
      digitalServiceMaturity: "developing",
      lendingBreadth: "moderate",
      operatingComplexityBand: "moderate",
      publicChangeSignals: [],
      regulatoryDataAvailability: "restricted_synthetic",
    },
  },
  {
    n: 5,
    displayName: "Silverpine Illustrative Bank",
    organizationType: "synthetic_bank",
    regionCode: "REGION_COAST_DEMO",
    localityLabel: "Illustrative Coast",
    tags: ["demo-complete", "bank"],
    payload: {
      institutionKind: "synthetic_bank",
      serviceAreaType: "national_synthetic",
      operatingRegions: ["REGION_COAST_DEMO", "REGION_WEST_DEMO", "REGION_SOUTH_DEMO"],
      balanceSheetScaleBand: "band_xl",
      ownershipModel: "synthetic_stock",
      digitalServiceMaturity: "established",
      lendingBreadth: "broad",
      operatingComplexityBand: "high",
      publicChangeSignals: [
        {
          label: "Synthetic digital channel launch",
          reference: "synthetic://financial-institutions/org_syn_fi_005/change/digital",
          observedAt: "2026-01-20T14:00:00.000Z",
        },
      ],
      regulatoryDataAvailability: "abundant_synthetic",
    },
  },
  {
    n: 6,
    displayName: "Mossvale Example Credit Union",
    organizationType: "synthetic_credit_union",
    regionCode: "REGION_MID_DEMO",
    localityLabel: "Illustrative Prairie",
    tags: ["demo-missing-provenance", "credit-union"],
    payload: {
      institutionKind: "synthetic_credit_union",
      serviceAreaType: "single_region",
      operatingRegions: ["REGION_MID_DEMO"],
      balanceSheetScaleBand: "band_s",
      ownershipModel: "synthetic_cooperative",
      digitalServiceMaturity: "emerging",
      lendingBreadth: "narrow",
      operatingComplexityBand: "low",
      publicChangeSignals: [],
      regulatoryDataAvailability: "sparse_synthetic",
    },
  },
  {
    n: 7,
    displayName: "Ironwick Sample Mutual Bank",
    organizationType: "synthetic_bank",
    regionCode: "REGION_NORTH_DEMO",
    localityLabel: "Illustrative Lakes",
    tags: ["bank", "demo-partial"],
    payload: {
      institutionKind: "synthetic_bank",
      serviceAreaType: "multi_region",
      operatingRegions: ["REGION_NORTH_DEMO", "REGION_MID_DEMO"],
      balanceSheetScaleBand: "band_l",
      ownershipModel: "synthetic_mutual",
      digitalServiceMaturity: "developing",
      lendingBreadth: "moderate",
      operatingComplexityBand: "moderate",
      publicChangeSignals: [],
      regulatoryDataAvailability: "moderate_synthetic",
    },
  },
  {
    n: 8,
    displayName: "Bluefen Demo Credit Union",
    organizationType: "synthetic_credit_union",
    regionCode: "REGION_WEST_DEMO",
    localityLabel: "Illustrative Desert",
    tags: ["credit-union"],
    payload: {
      institutionKind: "synthetic_credit_union",
      serviceAreaType: "single_region",
      operatingRegions: ["REGION_WEST_DEMO"],
      balanceSheetScaleBand: "band_m",
      ownershipModel: "synthetic_cooperative",
      digitalServiceMaturity: "established",
      lendingBreadth: "moderate",
      operatingComplexityBand: "moderate",
      publicChangeSignals: [],
      regulatoryDataAvailability: "moderate_synthetic",
    },
  },
  {
    n: 9,
    displayName: "Quartzfield Synthetic Bank",
    organizationType: "synthetic_bank",
    regionCode: "REGION_SOUTH_DEMO",
    localityLabel: "Illustrative Delta",
    tags: ["bank", "demo-complete"],
    payload: {
      institutionKind: "synthetic_bank",
      serviceAreaType: "single_region",
      operatingRegions: ["REGION_SOUTH_DEMO"],
      balanceSheetScaleBand: "band_m",
      ownershipModel: "synthetic_stock",
      digitalServiceMaturity: "developing",
      lendingBreadth: "broad",
      operatingComplexityBand: "moderate",
      publicChangeSignals: [],
      regulatoryDataAvailability: "abundant_synthetic",
    },
  },
  {
    n: 10,
    displayName: "Willowmere Example Institution",
    organizationType: "synthetic_credit_union",
    regionCode: "REGION_COAST_DEMO",
    localityLabel: "Illustrative Shore",
    tags: ["credit-union", "demo-stale"],
    payload: {
      institutionKind: "synthetic_credit_union",
      serviceAreaType: "multi_region",
      operatingRegions: ["REGION_COAST_DEMO", "REGION_NORTH_DEMO"],
      balanceSheetScaleBand: "band_l",
      ownershipModel: "synthetic_cooperative",
      digitalServiceMaturity: "established",
      lendingBreadth: "broad",
      operatingComplexityBand: "high",
      publicChangeSignals: [
        {
          label: "Synthetic membership program note",
          reference: "synthetic://financial-institutions/org_syn_fi_010/change/membership",
          observedAt: "2023-11-12T09:00:00.000Z",
        },
      ],
      regulatoryDataAvailability: "moderate_synthetic",
    },
  },
  {
    n: 11,
    displayName: "Redgrove Sample Credit Union",
    organizationType: "synthetic_credit_union",
    regionCode: "REGION_MID_DEMO",
    localityLabel: "Illustrative Heartland",
    tags: ["credit-union"],
    payload: {
      institutionKind: "synthetic_credit_union",
      serviceAreaType: "single_region",
      operatingRegions: ["REGION_MID_DEMO"],
      balanceSheetScaleBand: "band_s",
      ownershipModel: "synthetic_cooperative",
      digitalServiceMaturity: "emerging",
      lendingBreadth: "narrow",
      operatingComplexityBand: "low",
      publicChangeSignals: [],
      regulatoryDataAvailability: "sparse_synthetic",
    },
  },
  {
    n: 12,
    displayName: "Stoneharbor Demo Bank",
    organizationType: "synthetic_bank",
    regionCode: "REGION_NORTH_DEMO",
    localityLabel: "Illustrative Harbor",
    tags: ["bank", "demo-restricted"],
    payload: {
      institutionKind: "synthetic_bank",
      serviceAreaType: "national_synthetic",
      operatingRegions: ["REGION_NORTH_DEMO", "REGION_COAST_DEMO"],
      balanceSheetScaleBand: "band_xl",
      ownershipModel: "synthetic_stock",
      digitalServiceMaturity: "established",
      lendingBreadth: "broad",
      operatingComplexityBand: "high",
      publicChangeSignals: [],
      regulatoryDataAvailability: "restricted_synthetic",
    },
  },
  {
    n: 13,
    displayName: "Ashcroft Illustrative Credit Union",
    organizationType: "synthetic_credit_union",
    regionCode: "REGION_WEST_DEMO",
    localityLabel: "Illustrative Plateau",
    tags: ["credit-union", "demo-partial"],
    payload: {
      institutionKind: "synthetic_credit_union",
      serviceAreaType: "single_region",
      operatingRegions: ["REGION_WEST_DEMO"],
      balanceSheetScaleBand: "band_m",
      ownershipModel: "synthetic_cooperative",
      digitalServiceMaturity: "developing",
      lendingBreadth: "moderate",
      operatingComplexityBand: "moderate",
      publicChangeSignals: [],
      regulatoryDataAvailability: "moderate_synthetic",
    },
  },
  {
    n: 14,
    displayName: "Brightfen Synthetic Bank",
    organizationType: "synthetic_bank",
    regionCode: "REGION_SOUTH_DEMO",
    localityLabel: "Illustrative Bayou",
    tags: ["bank"],
    payload: {
      institutionKind: "synthetic_bank",
      serviceAreaType: "multi_region",
      operatingRegions: ["REGION_SOUTH_DEMO", "REGION_MID_DEMO"],
      balanceSheetScaleBand: "band_l",
      ownershipModel: "synthetic_mutual",
      digitalServiceMaturity: "developing",
      lendingBreadth: "moderate",
      operatingComplexityBand: "moderate",
      publicChangeSignals: [],
      regulatoryDataAvailability: "abundant_synthetic",
    },
  },
  {
    n: 15,
    displayName: "Maplewick Example Bank",
    organizationType: "synthetic_bank",
    regionCode: "REGION_MID_DEMO",
    localityLabel: "Illustrative Orchard",
    tags: ["bank", "demo-complete"],
    payload: {
      institutionKind: "synthetic_bank",
      serviceAreaType: "single_region",
      operatingRegions: ["REGION_MID_DEMO"],
      balanceSheetScaleBand: "band_s",
      ownershipModel: "synthetic_stock",
      digitalServiceMaturity: "emerging",
      lendingBreadth: "narrow",
      operatingComplexityBand: "low",
      publicChangeSignals: [],
      regulatoryDataAvailability: "moderate_synthetic",
    },
  },
  {
    n: 16,
    displayName: "Cloudmere Demo Credit Union",
    organizationType: "synthetic_credit_union",
    regionCode: "REGION_COAST_DEMO",
    localityLabel: "Illustrative Cliff",
    tags: ["credit-union"],
    payload: {
      institutionKind: "synthetic_credit_union",
      serviceAreaType: "single_region",
      operatingRegions: ["REGION_COAST_DEMO"],
      balanceSheetScaleBand: "band_m",
      ownershipModel: "synthetic_cooperative",
      digitalServiceMaturity: "established",
      lendingBreadth: "moderate",
      operatingComplexityBand: "moderate",
      publicChangeSignals: [],
      regulatoryDataAvailability: "abundant_synthetic",
    },
  },
  {
    n: 17,
    displayName: "Emberford Sample Institution",
    organizationType: "synthetic_bank",
    regionCode: "REGION_WEST_DEMO",
    localityLabel: "Illustrative Canyon",
    tags: ["bank", "demo-missing-provenance"],
    payload: {
      institutionKind: "synthetic_bank",
      serviceAreaType: "single_region",
      operatingRegions: ["REGION_WEST_DEMO"],
      balanceSheetScaleBand: "band_m",
      ownershipModel: "synthetic_stock",
      digitalServiceMaturity: "developing",
      lendingBreadth: "moderate",
      operatingComplexityBand: "moderate",
      publicChangeSignals: [],
      regulatoryDataAvailability: "sparse_synthetic",
    },
  },
  {
    n: 18,
    displayName: "Frostglen Synthetic Credit Union",
    organizationType: "synthetic_credit_union",
    regionCode: "REGION_NORTH_DEMO",
    localityLabel: "Illustrative Ridge",
    tags: ["credit-union", "demo-stale"],
    payload: {
      institutionKind: "synthetic_credit_union",
      serviceAreaType: "multi_region",
      operatingRegions: ["REGION_NORTH_DEMO", "REGION_MID_DEMO"],
      balanceSheetScaleBand: "band_l",
      ownershipModel: "synthetic_cooperative",
      digitalServiceMaturity: "established",
      lendingBreadth: "broad",
      operatingComplexityBand: "high",
      publicChangeSignals: [
        {
          label: "Synthetic systems refresh note",
          reference: "synthetic://financial-institutions/org_syn_fi_018/change/systems",
          observedAt: "2024-01-05T11:00:00.000Z",
        },
      ],
      regulatoryDataAvailability: "moderate_synthetic",
    },
  },
  {
    n: 19,
    displayName: "Sandpiper Illustrative Bank",
    organizationType: "synthetic_bank",
    regionCode: "REGION_COAST_DEMO",
    localityLabel: "Illustrative Inlet",
    tags: ["bank"],
    payload: {
      institutionKind: "synthetic_bank",
      serviceAreaType: "national_synthetic",
      operatingRegions: ["REGION_COAST_DEMO", "REGION_SOUTH_DEMO", "REGION_WEST_DEMO"],
      balanceSheetScaleBand: "band_xl",
      ownershipModel: "synthetic_stock",
      digitalServiceMaturity: "established",
      lendingBreadth: "broad",
      operatingComplexityBand: "high",
      publicChangeSignals: [],
      regulatoryDataAvailability: "abundant_synthetic",
    },
  },
  {
    n: 20,
    displayName: "Thornfield Demo Credit Union",
    organizationType: "synthetic_credit_union",
    regionCode: "REGION_SOUTH_DEMO",
    localityLabel: "Illustrative Grove",
    tags: ["credit-union", "demo-partial"],
    payload: {
      institutionKind: "synthetic_credit_union",
      serviceAreaType: "single_region",
      operatingRegions: ["REGION_SOUTH_DEMO"],
      balanceSheetScaleBand: "band_s",
      ownershipModel: "synthetic_cooperative",
      digitalServiceMaturity: "emerging",
      lendingBreadth: "narrow",
      operatingComplexityBand: "low",
      publicChangeSignals: [],
      regulatoryDataAvailability: "sparse_synthetic",
    },
  },
  {
    n: 21,
    displayName: "Oakspire Sample Bank",
    organizationType: "synthetic_bank",
    regionCode: "REGION_MID_DEMO",
    localityLabel: "Illustrative Plains",
    tags: ["bank", "demo-complete"],
    payload: {
      institutionKind: "synthetic_bank",
      serviceAreaType: "multi_region",
      operatingRegions: ["REGION_MID_DEMO", "REGION_SOUTH_DEMO"],
      balanceSheetScaleBand: "band_l",
      ownershipModel: "synthetic_mutual",
      digitalServiceMaturity: "developing",
      lendingBreadth: "moderate",
      operatingComplexityBand: "moderate",
      publicChangeSignals: [],
      regulatoryDataAvailability: "moderate_synthetic",
    },
  },
  {
    n: 22,
    displayName: "Riverknot Example Credit Union",
    organizationType: "synthetic_credit_union",
    regionCode: "REGION_NORTH_DEMO",
    localityLabel: "Illustrative Valley",
    tags: ["credit-union"],
    payload: {
      institutionKind: "synthetic_credit_union",
      serviceAreaType: "single_region",
      operatingRegions: ["REGION_NORTH_DEMO"],
      balanceSheetScaleBand: "band_m",
      ownershipModel: "synthetic_cooperative",
      digitalServiceMaturity: "established",
      lendingBreadth: "moderate",
      operatingComplexityBand: "moderate",
      publicChangeSignals: [],
      regulatoryDataAvailability: "abundant_synthetic",
    },
  },
  {
    n: 23,
    displayName: "Nightingale Synthetic Bank",
    organizationType: "synthetic_bank",
    regionCode: "REGION_WEST_DEMO",
    localityLabel: "Illustrative Mesa",
    tags: ["bank", "demo-restricted"],
    payload: {
      institutionKind: "synthetic_bank",
      serviceAreaType: "single_region",
      operatingRegions: ["REGION_WEST_DEMO"],
      balanceSheetScaleBand: "band_m",
      ownershipModel: "synthetic_stock",
      digitalServiceMaturity: "developing",
      lendingBreadth: "moderate",
      operatingComplexityBand: "moderate",
      publicChangeSignals: [],
      regulatoryDataAvailability: "restricted_synthetic",
    },
  },
  {
    n: 24,
    displayName: "Paperlantern Demo Credit Union",
    organizationType: "synthetic_credit_union",
    regionCode: "REGION_COAST_DEMO",
    localityLabel: "Illustrative Marsh",
    tags: ["credit-union", "demo-complete"],
    payload: {
      institutionKind: "synthetic_credit_union",
      serviceAreaType: "multi_region",
      operatingRegions: ["REGION_COAST_DEMO", "REGION_SOUTH_DEMO"],
      balanceSheetScaleBand: "band_l",
      ownershipModel: "synthetic_cooperative",
      digitalServiceMaturity: "established",
      lendingBreadth: "broad",
      operatingComplexityBand: "high",
      publicChangeSignals: [
        {
          label: "Synthetic community program note",
          reference: "synthetic://financial-institutions/org_syn_fi_024/change/community",
          observedAt: "2026-02-28T16:00:00.000Z",
        },
      ],
      regulatoryDataAvailability: "abundant_synthetic",
    },
  },
];

function pad(n: number): string {
  return String(n).padStart(3, "0");
}

export function buildSyntheticOrganizations(): readonly Organization[] {
  if (SEEDS.length !== 24) {
    throw new Error(`Expected 24 synthetic organizations, found ${SEEDS.length}`);
  }

  return Object.freeze(
    SEEDS.map((seed) => {
      const id = `org_syn_fi_${pad(seed.n)}`;
      const payload: FinancialInstitutionPayload = {
        schemaVersion: "1.0.0",
        syntheticDeclaration: DATASET_DECLARATION,
        ...seed.payload,
      };
      return parseOrganization({
        id,
        tenantId: DEMO_DOMAIN_TENANT_ID,
        verticalId: FINANCIAL_INSTITUTIONS_VERTICAL_ID,
        adapterVersion: FINANCIAL_INSTITUTIONS_ADAPTER_VERSION,
        displayName: seed.displayName,
        legalName: seed.legalName,
        organizationType: seed.organizationType,
        lifecycleStatus: "active",
        primaryLocation: {
          regionCode: seed.regionCode,
          localityLabel: seed.localityLabel,
          countryCode: "XX",
        },
        summary: `Synthetic demonstration record for ${seed.displayName}. Not a real organization.`,
        tags: seed.tags,
        externalReferences: [
          {
            kind: "synthetic_internal",
            label: "Synthetic fixture record",
            reference: `synthetic://financial-institutions/${id}`,
          },
        ],
        createdAt: CREATED,
        updatedAt: UPDATED,
        synthetic: true,
        dataClassification: "synthetic",
        fit: { status: "unassessed" },
        domainSchemaVersion: "1.0.0",
        verticalPayload: payload,
      });
    }),
  );
}
